### ISSUE TITLE
PostGIS Geoprocessing 0.8 won't work with QGIS 2.16.2

### ISSUE THREAD

**Issue by M-Rick** [NaturalGIS/postgis_geoprocessing#20]
I update PostGIS Geoprocessing to version 0.8 but I got an error:

```
Version de Python : 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] 
Version de QGIS : 2.16.2 Nødebo, exported 

Chemin Python :
/Users/aymeric/.qgis2/python/plugins/ScipyPointClustering
/Users/aymeric/.qgis2/python/plugins/processing
/Users/aymeric/.qgis2/python/plugins/geoserverexplorer/ext-libs/httplib2-0.8-py2.7.egg
/Users/aymeric/.qgis2/python/plugins/geoserverexplorer/ext-libs/python_dateutil-2.2-py2.7.egg
/Users/aymeric/.qgis2/python/plugins/geoserverexplorer/ext-libs/six-1.10.0-py2.7.egg
/Users/aymeric/.qgis2/python/plugins/geoserverexplorer/ext-libs/requests-2.5.0-py2.7.egg
/Users/aymeric/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.6-py2.7.egg
/Users/aymeric/.qgis2/python/plugins/webappbuilder/ext-libs/jsmin-2.2.1-py2.7.egg
/Users/aymeric/.qgis2/python/plugins/webappbuilder/ext-libs/gsconfig-1.0.3-py2.7.egg
/Users/aymeric/.qgis2/python/plugins/webappbuilder/ext-libs/gisdata-0.5.4-py2.7.egg
/Users/aymeric/.qgis2/python/plugins/webappbuilder/ext-libs/httplib2-0.9.2-py2.7.egg
/Users/aymeric/.qgis2/python/plugins/webappbuilder/ext-libs/requests-2.9.1-py2.7.egg
/Users/aymeric/.qgis2/python/plugins/webappbuilder/ext-libs/jsbeautifier-1.6.2-py2.7.egg
/Users/aymeric/.qgis2/python/plugins/webappbuilder/ext-libs/six-1.10.0-py2.7.egg
/Users/aymeric/.qgis2/python/plugins/webappbuilder/ext-libs/BeautifulSoup-3.2.1-py2.7.egg
/Users/aymeric/.qgis2/python/plugins/geoserverexplorer/ext-libs/gisdata-0.5.4-py2.7.egg
/Users/aymeric/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsimporter-1.0.0-py2.7.egg
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/aymeric/.qgis2/python
/Users/aymeric/.qgis2/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/C/Python/2.7
/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7/site-packages
/Library/Python/2.7/site-packages/scipy-override
/Library/Python/2.7/site-packages/numpy-override
/Library/Python/2.7/site-packages/matplotlib-override
/Library/Frameworks/GDAL.framework/Versions/2.1/Python/2.7/site-packages
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC
/Library/Python/2.7/site-packages
/Library/Python/2.7/site-packages/PIL
/Users/aymeric/.qgis2//python
/Users/aymeric/.qgis2/python/plugins/DigitizingTools/tools
/Users/aymeric/.qgis2/python/plugins/geoserverexplorer/ext-libs
/Users/aymeric/.qgis2/python/plugins/mmqgis/forms
.
/Users/aymeric/.qgis2/python/plugins
/Users/aymeric/.qgis2/python/plugins/webappbuilder/ext-libs
/Users/aymeric/.qgis2/python/plugins/webappbuilder
```

Log:

```
2016-09-27T16:59:31 1   Traceback (most recent call last):
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 308, in loadPlugin
                __import__(packageName)
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
                mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/Users/aymeric/.qgis2/python/plugins/postgis_geoprocessing/__init__.py", line 28, in <module>
                from postgis_geoprocessing.OgrGeoprocessingProviderPlugin import \
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
                mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/Users/aymeric/.qgis2/python/plugins/postgis_geoprocessing/OgrGeoprocessingProviderPlugin.py", line 35, in <module>
                from postgis_geoprocessing.OgrGeoprocessingProvider import OgrGeoprocessingProvider
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
                mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/Users/aymeric/.qgis2/python/plugins/postgis_geoprocessing/OgrGeoprocessingProvider.py", line 36, in <module>
                from postgis_geoprocessing.distance import distance
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
                mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/Users/aymeric/.qgis2/python/plugins/postgis_geoprocessing/distance.py", line 48, in <module>
                from processing.tools.vector import ogrConnectionString, ogrLayerName
            ImportError: cannot import name ogrConnectionString

2016-09-27T16:59:35 1   Traceback (most recent call last):
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 308, in loadPlugin
                __import__(packageName)
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
                mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/Users/aymeric/.qgis2/python/plugins/postgis_geoprocessing/__init__.py", line 28, in <module>
                from postgis_geoprocessing.OgrGeoprocessingProviderPlugin import \
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
                mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/Users/aymeric/.qgis2/python/plugins/postgis_geoprocessing/OgrGeoprocessingProviderPlugin.py", line 35, in <module>
                from postgis_geoprocessing.OgrGeoprocessingProvider import OgrGeoprocessingProvider
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
                mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/Users/aymeric/.qgis2/python/plugins/postgis_geoprocessing/OgrGeoprocessingProvider.py", line 36, in <module>
                from postgis_geoprocessing.distance import distance
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
                mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/Users/aymeric/.qgis2/python/plugins/postgis_geoprocessing/distance.py", line 48, in <module>
                from processing.tools.vector import ogrConnectionString, ogrLayerName
            ImportError: cannot import name ogrConnectionString
```

**Comment by gioman** [comment]
> I update PostGIS Geoprocessing to version 0.8 but I got an error:

Hi, did a previous version of the plugin worked on the same QGIS version on OsX?

**Comment by M-Rick** [comment]
Yes version 0.7 works well.

**Comment by gioman** [comment]
> Yes version 0.7 works well.

Hi, just tested 0.8 on OsX El Capitan, with QGIS 2.16.3 and it all ok here. Please check in inside 

~/.qgis2/python/plugins

you have a "processing" folder, if yes delete it and restart qgis.

cheers!
